---
- name: Include OS specific variables
  ansible.builtin.include_vars: "{{ _file }}"
  vars:
    _file: "{{ lookup('first_found', _params) }}"
    _params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release | default('') }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}.yml"
        - fallback.yml
      paths:
        - "{{ role_path }}/vars"

- name: Validate OS is supported
  ansible.builtin.assert:
    that:
      - _zbxproxy_os_is_supported
    fail_msg: "This role does not support {{ ansible_distribution }} {{ ansible_distribution_version }}."
    success_msg: "This role supports {{ ansible_distribution }} {{ ansible_distribution_version }}."

- name: Indicate OS is tested
  when:
    - _zbxproxy_os_is_tested
  ansible.builtin.debug:
    msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} has been tested with this role."

- name: Warn if OS is not tested
  when:
    - not _zbxproxy_os_is_tested
  ansible.builtin.debug:
    msg: "WARNING: {{ ansible_distribution }} {{ ansible_distribution_version }} is not tested."
  changed_when: true

- name: Validate Zabbix major version
  ansible.builtin.assert:
    that:
      - zbxproxy_major_version in _zbxproxy_supported_major_versions
    fail_msg: "This role does not support Zabbix Proxy {{ zbxproxy_major_version }} on {{ ansible_distribution }} {{ ansible_distribution_version }}."
    success_msg: "This role supports Zabbix Proxy {{ zbxproxy_major_version }} on {{ ansible_distribution }} {{ ansible_distribution_version }}."
