---
_zbx_os_is_supported: true
_zbx_os_is_tested: true

_zbx_repo_package_url_by_major_version:
  '7.4': https://repo.zabbix.com/zabbix/7.4/release/rhel/10/noarch/zabbix-release-latest-7.4.el10.noarch.rpm
  '7.0': https://repo.zabbix.com/zabbix/7.0/rhel/10/x86_64/zabbix-release-latest-7.0.el10.noarch.rpm

_zbx_gpg_keys:
  - https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-B5333005
  - https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-08EFA7DD

_zbx_repo_package_url: "{{ _zbx_repo_package_url_by_major_version[zbx_major_version] }}"
