---
- name: Ensure Zabbix GPG keys are installed
  loop: "{{ _zbx_gpg_keys }}"
  become: true
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: present

- name: Ensure Zabbix repositories are installed
  become: true
  ansible.builtin.dnf:
    name: "{{ _zbx_repo_package_url }}"
    state: present
    disable_gpg_check: true
