---
name: Generate Role Docs
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/agent2/.aar_doc.yml
      - roles/agent2/README.md
      - roles/agent2/meta/argument_specs.yml
      - roles/agent2/meta/main.yml
      - roles/host/.aar_doc.yml
      - roles/host/README.md
      - roles/host/meta/argument_specs.yml
      - roles/host/meta/main.yml
      - roles/nginx/.aar_doc.yml
      - roles/nginx/README.md
      - roles/nginx/meta/argument_specs.yml
      - roles/nginx/meta/main.yml
      - roles/proxy/.aar_doc.yml
      - roles/proxy/README.md
      - roles/proxy/meta/argument_specs.yml
      - roles/proxy/meta/main.yml
      - roles/proxy_postgresql/.aar_doc.yml
      - roles/proxy_postgresql/README.md
      - roles/proxy_postgresql/meta/argument_specs.yml
      - roles/proxy_postgresql/meta/main.yml
      - roles/proxy_sqlite3/.aar_doc.yml
      - roles/proxy_sqlite3/README.md
      - roles/proxy_sqlite3/meta/argument_specs.yml
      - roles/proxy_sqlite3/meta/main.yml
      - roles/repo/.aar_doc.yml
      - roles/repo/README.md
      - roles/repo/meta/argument_specs.yml
      - roles/repo/meta/main.yml
      - roles/server/.aar_doc.yml
      - roles/server/README.md
      - roles/server/meta/argument_specs.yml
      - roles/server/meta/main.yml
      - roles/server_postgresql/.aar_doc.yml
      - roles/server_postgresql/README.md
      - roles/server_postgresql/meta/argument_specs.yml
      - roles/server_postgresql/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.zabbix'
jobs:
  docs_agent2:
    name: Generate agent2 role documentation
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.zabbix
          ref: main
      - name: Generate agent2 role documentation
        working-directory: 'trippsc2.zabbix'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/agent2
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update agent2 role documentation." || /bin/true
          git push origin main
          deactivate
  docs_host:
    name: Generate host role documentation
    needs: docs_agent2
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.zabbix
          ref: main
      - name: Generate host role documentation
        working-directory: 'trippsc2.zabbix'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/host
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update host role documentation." || /bin/true
          git push origin main
          deactivate
  docs_nginx:
    name: Generate nginx role documentation
    needs: docs_host
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.zabbix
          ref: main
      - name: Generate nginx role documentation
        working-directory: 'trippsc2.zabbix'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/nginx
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update nginx role documentation." || /bin/true
          git push origin main
          deactivate
  docs_proxy:
    name: Generate proxy role documentation
    needs: docs_nginx
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.zabbix
          ref: main
      - name: Generate proxy role documentation
        working-directory: 'trippsc2.zabbix'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/proxy
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update proxy role documentation." || /bin/true
          git push origin main
          deactivate
  docs_proxy_postgresql:
    name: Generate proxy_postgresql role documentation
    needs: docs_proxy
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.zabbix
          ref: main
      - name: Generate proxy_postgresql role documentation
        working-directory: 'trippsc2.zabbix'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/proxy_postgresql
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update proxy_postgresql role documentation." || /bin/true
          git push origin main
          deactivate
  docs_proxy_sqlite3:
    name: Generate proxy_sqlite3 role documentation
    needs: docs_proxy_postgresql
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.zabbix
          ref: main
      - name: Generate proxy_sqlite3 role documentation
        working-directory: 'trippsc2.zabbix'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/proxy_sqlite3
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update proxy_sqlite3 role documentation." || /bin/true
          git push origin main
          deactivate
  docs_repo:
    name: Generate repo role documentation
    needs: docs_proxy_sqlite3
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.zabbix
          ref: main
      - name: Generate repo role documentation
        working-directory: 'trippsc2.zabbix'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/repo
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update repo role documentation." || /bin/true
          git push origin main
          deactivate
  docs_server:
    name: Generate server role documentation
    needs: docs_repo
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.zabbix
          ref: main
      - name: Generate server role documentation
        working-directory: 'trippsc2.zabbix'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/server
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update server role documentation." || /bin/true
          git push origin main
          deactivate
  docs_server_postgresql:
    name: Generate server_postgresql role documentation
    needs: docs_server
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.zabbix
          ref: main
      - name: Generate server_postgresql role documentation
        working-directory: 'trippsc2.zabbix'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/server_postgresql
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update server_postgresql role documentation." || /bin/true
          git push origin main
          deactivate
