---
name: Release collection
'on':
  push:
    tags:
      - '*'
defaults:
  run:
    working-directory: 'trippsc2.zabbix'
jobs:
  release:
    name: Release collection
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.zabbix
      - name: Release collection
        working-directory: 'trippsc2.zabbix'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          ansible-galaxy collection build --force
          ansible-galaxy collection publish --token "${{ secrets.GALAXY_API_KEY }}" *.tar.gz
          rm -rf *.tar.gz
          deactivate
